export enum AutoSearchType {
  ATTRIBUTE_SEARCH = "ATTRIBUTE_SEARCH",
  CATEGORY_SEARCH = "CATEGORY_SEARCH",
  UOM_SEARCH = "UOM_SEARCH",
  PRODUCT_SEARCH = "PRODUCT_SEARCH",
  PARTNER_SEARCH = "PARTNER_SEARCH",
}